apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleapp
spec:
  selector:
    matchLabels:
      name: simpleapp
  template:
    metadata:
      labels:
        name: simpleapp
    spec:
      containers:
      - name: myapp
        image: minalmahor/mycluster
        ports:
        - containerPort: 30017
